name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install latex
      run: |
        sudo apt-get install -y latexmk texlive texlive-latex-extra texlive-science texlive-fonts-extra

    - name: Build
      run: |
        latexmk -f -pdf -file-line-error -interaction=nonstopmode thesis.tex || true
        cp -r thesis.pdf out/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
